# Generated by Django 5.0.6 on 2024-06-14 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apoderados', '0002_alter_apoderado_fecha_nacimiento'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_transaccion', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=8)),
                ('categoria', models.CharField(choices=[('Pago de Plan', 'Pago de Plan'), ('Servicio', 'Serivicio'), ('Utensilios', 'Utensilios'), ('Arriendo Local', 'Arriendo Local')], max_length=16)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=30)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('apoderado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apoderados.apoderado')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
            ],
        ),
    ]
