# Generated by Django 5.0.6 on 2024-05-17 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apoderados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(max_length=30)),
                ('tercer_nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('primer_apellido', models.CharField(max_length=40)),
                ('segundo_apellido', models.CharField(max_length=40)),
                ('rut', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='apoderados.apoderado')),
            ],
        ),
    ]
