# Generated by Django 5.0.6 on 2024-07-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoderados', '0002_alter_apoderado_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoderado',
            name='rut',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
