# Generated by Django 5.0.6 on 2024-07-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoderados', '0003_alter_apoderado_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoderado',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
