# Generated by Django 5.0.6 on 2024-07-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apoderados', '0004_alter_apoderado_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoderado',
            name='telefono',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
