# Generated by Django 5.0.6 on 2024-05-18 00:44

import asistencia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(default=asistencia.models.get_current_date),
        ),
    ]
